import { describe, expect, it } from 'vitest'
import { parseImportBody, readReelImportBody, readReelVideoBody, reelVideoPreflight, safeIdempotencyKey, safeImportId, safeSourceURL } from '../src/lib/reelImportHTTP'
import { edgeIngressSignature, verifyEdgeIngressSignature } from '../src/lib/edgeIngressSignature'

const key = 'f67f3517-956a-4f4e-a224-631cb43d8edf'

describe('reel import HTTP boundary', () => {
  it('accepts only a bounded object with a valid request ID', () => {
    expect(parseImportBody('{"sourceURL":"https://www.instagram.com/reel/ABC123xyz/"}')).not.toBeNull()
    expect(parseImportBody('[]')).toBeNull()
    expect(parseImportBody('{')).toBeNull()
    expect(safeIdempotencyKey(key.toUpperCase())).toBe(key)
    expect(safeIdempotencyKey('not-a-uuid')).toBeNull()
    expect(safeImportId('j57abc123')).toBe('j57abc123')
    expect(safeImportId('../other-owner')).toBeNull()
    expect(safeSourceURL(undefined)).toBeUndefined()
    expect(safeSourceURL(undefined, true)).toBeNull()
    expect(safeSourceURL('x'.repeat(2049))).toBeNull()
  })

  it('rejects oversized declared and streamed callback bodies', async () => {
    const declared = new Request('https://example.test/callback', {
      method: 'POST', headers: { 'content-length': '40000' }, body: '{}',
    })
    expect(await readReelImportBody(declared)).toBeNull()

    const chunked = new Request('https://example.test/callback', {
      method: 'POST', body: 'x'.repeat(33 * 1024),
    })
    expect(await readReelImportBody(chunked)).toBeNull()
  })

  it('rejects unsupported or oversized video before reserving storage', () => {
    expect(reelVideoPreflight(new Headers({ 'content-type': 'text/plain' }))).toMatchObject({ ok: false, status: 415 })
    expect(reelVideoPreflight(new Headers({ 'content-type': 'video/mp4', 'content-length': '20000001' })))
      .toMatchObject({ ok: false, status: 413 })
    expect(reelVideoPreflight(new Headers({ 'content-type': 'video/quicktime', 'content-length': '20000000' })))
      .toMatchObject({ ok: true, contentType: 'video/quicktime' })
    expect(reelVideoPreflight(new Headers({ 'content-type': 'video/mp4', 'content-length': 'NaN' })))
      .toMatchObject({ ok: false, status: 413 })
  })

  it('rejects empty and oversized chunked videos before any upload mutation', async () => {
    const empty = new Request('https://example.test/upload', { method: 'POST', body: '' })
    expect(await readReelVideoBody(empty, 'video/mp4')).toBeNull()
    const oversized = new Request('https://example.test/upload', {
      method: 'POST', body: 'x'.repeat(20_000_001),
    })
    expect(await readReelVideoBody(oversized, 'video/mp4')).toBeNull()
    const valid = new Request('https://example.test/upload', { method: 'POST', body: 'video' })
    expect((await readReelVideoBody(valid, 'video/mp4'))?.size).toBe(5)
  })

  it('verifies Modal-compatible HMAC over the untouched body in a five-minute window', async () => {
    // Fixed vector generated by modal/reel_import_core.py, not by this JS helper.
    expect(await edgeIngressSignature('{"ok":true}', 'shared-secret', 123))
      .toBe('t=123,v1=c79f9c1ccd77fffdb6311a1ce1c4c2182c00089dd1069d7c5d396f16f909cd1b')
    const rawBody = '{"importId":"j57abc123","status":"completed"}'
    const timestamp = 1_700_000_000
    const signatureHeader = await edgeIngressSignature(rawBody, 'modal-test-secret', timestamp)
    expect(await verifyEdgeIngressSignature({ rawBody, signatureHeader, signingSecret: 'modal-test-secret', nowSeconds: timestamp + 30 })).toBe(true)
    expect(await verifyEdgeIngressSignature({ rawBody: `${rawBody} `, signatureHeader, signingSecret: 'modal-test-secret', nowSeconds: timestamp })).toBe(false)
    expect(await verifyEdgeIngressSignature({ rawBody, signatureHeader, signingSecret: 'modal-test-secret', nowSeconds: timestamp + 301 })).toBe(false)
  })
})
